### ISSUE TITLE
Magento 2.4.4 and PHP 8.1 compatibility

### ISSUE THREAD

**Issue by lucasmilin** [cmdotcom-plugins/pay-ext-magento2#13]
Could you please add Magento 2.4.4, 2.4.5 and PHP 8.1 compatibility as it is the new version?

PHP 7.4 end of life is on 28 Nov 2022

**Comment by bbakalov** [comment]
@lucasmilin I'm on it

**Comment by lucasmilin** [comment]
Hey @bbakalov! Do you have an ETA for this task? Our website is built on top of Magento Commerce 2.4.5 and we would like to plan to integrate CM payment.

Thanks a lot!

**Comment by bbakalov** [comment]
Hello @lucasmilin, sorry, but can't give you ETA. 
I hope it will be released soon.

**Comment by stijnvandervegt** [comment]
Merged: https://github.com/cmdotcom-plugins/pay-ext-magento2/pull/14

**Comment by bbakalov** [comment]
Hey @lucasmilin as I see changes have been added and now it should be compatible. Please test it.
